import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Home_Page extends javax.swing.JFrame {
	private User activeUser;
    /**
     * Creates new form HomePage
     */
    public Home_Page(User activeUser) {
    	this.activeUser = activeUser;
        initComponents();
        post(4);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        SearchButton = new javax.swing.JButton();
        GroupButton = new javax.swing.JButton();
        FriendsButton = new javax.swing.JButton();
        TimelineButton = new javax.swing.JButton();
        MorePostsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchButton.setText("Search");

        GroupButton.setText("Groups");

        FriendsButton.setText("Friends");

        TimelineButton.setText("Timeline");

        MorePostsButton.setText("More Posts");
        
        SearchButton.addActionListener(new SearchActionListener());
        GroupButton.addActionListener(new groupsActionListener());
        FriendsButton.addActionListener(new friendsActionListener());
        TimelineButton.addActionListener(new timelineActionListener());
        MorePostsButton.addActionListener(new nextpostsActionListener());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(GroupButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(FriendsButton)
                .addGap(18, 22, Short.MAX_VALUE)
                .addComponent(TimelineButton)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MorePostsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton)
                    .addComponent(GroupButton)
                    .addComponent(FriendsButton)
                    .addComponent(TimelineButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(MorePostsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    class SearchActionListener implements ActionListener
	{
		public void actionPerformed(ActionEvent e)
		{
			//TODO 
			new SearchScreen(activeUser);
		}

	}
	class groupsActionListener implements ActionListener
	{
		public void actionPerformed(ActionEvent e)
		{
			DisplayLists.createAndShowGUI(activeUser,null ,activeUser.getGroups() );
		}

	}
	class friendsActionListener implements ActionListener
	{
		public void actionPerformed(ActionEvent e)
		{
			DisplayLists.createAndShowGUI(activeUser,activeUser.getFriends() ,null );
		}

	}
	class timelineActionListener implements ActionListener
	{
		public void actionPerformed(ActionEvent e)
		{
			new User_Timeline(activeUser, activeUser);// Because the activeUser wants to go to his Timeline
		}

	}
	class nextpostsActionListener implements ActionListener
	{
		public void actionPerformed(ActionEvent e)
		{
			//TODO
			post(5);
		}

	}
	
	public void post(int numberOfPosts){//the number of posts to be displayed
		




	}

    

        
        
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton FriendsButton;
    private javax.swing.JButton GroupButton;
    private javax.swing.JButton MorePostsButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton TimelineButton;
    // End of variables declaration                   
}
