import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class User_Timeline extends javax.swing.JFrame {
	private User activeUser, friend;
	/**
	 * Creates new form UserTimeline
	 */
	public User_Timeline(User activeuser,User friend) {
		this.friend = friend;
		this.activeUser=activeuser;

		initComponents();




	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		SearchButton = new javax.swing.JButton();
		GroupsButton = new javax.swing.JButton();
		commonFriendsButton = new javax.swing.JButton();
		isFriends = new javax.swing.JToggleButton();
		morePostsButton = new javax.swing.JButton();
		postToTimelineButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		SearchButton.setText("Search");
		SearchButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SearchButtonActionPerformed(evt);
			}
		});

		GroupsButton.setText("Groups");
		GroupsButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				GroupsButtonActionPerformed(evt);
			}
		});

		commonFriendsButton.setText("Common Friends");
		commonFriendsButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				commonFriendsButtonActionPerformed(evt);
			}
		});

		isFriends.setText("jToggleButton1");

		morePostsButton.setText("More Posts");
		morePostsButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				morePostsButtonActionPerformed(evt);
			}
		});

		postToTimelineButton.setText("Post to Timeline");
		postToTimelineButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				postToTimelineButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(morePostsButton)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(SearchButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(GroupsButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(commonFriendsButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(postToTimelineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(isFriends, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(SearchButton)
								.addComponent(GroupsButton)
								.addComponent(commonFriendsButton)
								.addComponent(isFriends))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(postToTimelineButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
						.addComponent(morePostsButton))
				);

		pack();
	}// </editor-fold>                        

	private void morePostsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
		// TODO add your handling code here:
	}                                               
       
		class SearchButtonActionPerformed implements ActionListener
		{
			public void actionPerformed(ActionEvent e)
			{
				new SearchScreen(activeUser);
			}
		}                                         
                                             
		class GroupsButtonActionPerformed implements ActionListener
		{
			public void actionPerformed(ActionEvent e)
			{
				//TODO
				new DisplayLists(activeUser, activeUser.getFriends(), activeUser.getGroups());
			}
		}                                          

	private void commonFriendsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
		// TODO add your handling code here:
	}                                                   

	private void postToTimelineButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
		// TODO add your handling code here:
	}                                                    



	// Variables declaration - do not modify                     
	private javax.swing.JButton GroupsButton;
	private javax.swing.JButton SearchButton;
	private javax.swing.JButton commonFriendsButton;
	private javax.swing.JToggleButton isFriends;
	private javax.swing.JButton morePostsButton;
	private javax.swing.JButton postToTimelineButton;
	// End of variables declaration                   
}


/*class AddFriendListener implements ActionListener{
	public void actionPerformed(ActionEvent e){
		activeUser.addFriend(friend);
		addfriend.setEnabled(false);
		DataBase.save();
		deletefriend.setEnabled(true);
	}

}

class DeleteFriendListener implements ActionListener{
	public void actionPerformed(ActionEvent e){
		activeUser.removeFriend(friend);
		addfriend.setEnabled(true);
		DataBase.save();
		deletefriend.setEnabled(false);
	}

}*/

class BackListener implements ActionListener{
	public void actionPerformed(ActionEvent e){
		setVisible(false);
	}

}

class CommonFriendsListener implements ActionListener{
	public void actionPerformed(ActionEvent e){

	}
}

class NextPostsListener implements ActionListener{
	public void actionPerformed(ActionEvent e){

	}
}

class SearchActionListener implements ActionListener
{
	public void actionPerformed(ActionEvent e)
	{
		new SearchScreen(activeUser);
	}

}
class groupsActionListener implements ActionListener
{
	public void actionPerformed(ActionEvent e)
	{
		//TODO
		new DisplayLists(activeUser, activeUser.getFriends(), activeUser.getGroups());
	}

}


}

